- name: Query APIC
  hosts: aci
  connection: local
  gather_facts: false
  
  tasks:
  - name: Query all tenants
    aci_tenant:
      hostname: '{{ ansible_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      state: query
    register: all_tenants

  - debug:
      var: all_tenants

  - local_action:
      module: copy
      content: "{{ item.fvTenant.attributes }}"
      dest: ./Tenant_{{ item.fvTenant.attributes.name }}_JSON
    with_items:
      - "{{ all_tenants.current }}"